// WebHub — Language Data
const LANG = {
  zh: {
    navServices: '服务产品',
    navTemplates: '网站模板',
    navProcess: '合作流程',
    navPricing: '价格方案',
    navCTA: '立即咨询',
    heroTitle: '打造你的',
    heroHighlight: '专属网站',
    heroSub: '专业定制开发 · 精美模板即选即用 · 全响应式设计',
    heroBtn1: '了解服务',
    heroBtn2: '免费咨询',
    secServices: '服务产品',
    servicesDesc: '从个人品牌到企业官网，覆盖全场景需求',
    sv1Title: '企业官网定制', sv1Desc: '量身打造企业品牌官网，包含公司介绍、产品展示、新闻动态、在线留言等模块，助力企业形象升级。',
    sv2Title: '电商商城搭建', sv2Desc: '商品展示、购物车、在线支付、订单管理，一站式电商解决方案，快速开启线上销售渠道。',
    sv3Title: '响应式 H5 页面', sv3Desc: '活动推广、产品发布、品牌故事等单页/多页 H5，完美适配手机、平板、电脑等所有设备。',
    sv4Title: 'UI 设计 + 前端开发', sv4Desc: '专业的 UI 视觉设计配合高质量前端代码实现，像素级还原设计稿，流畅用户体验。',
    sv5Title: '网站维护 & 优化', sv5Desc: '内容更新、性能优化、安全加固、SEO 优化，让你的网站持续保持最佳状态。',
    sv6Title: '小程序开发', sv6Desc: '微信小程序、支付宝小程序定制开发，与网站数据互通，覆盖更多用户触达渠道。',
    tagPopular: '热门', tagRecommended: '推荐', tagNew: '新',
    secTemplates: '精选模板',
    templatesDesc: '即选即用，快速上线，专业设计品质',
    t1Title: '企业官网模板', t1Desc: '大气稳重风格，适合制造、科技、服务业',
    t2Title: '电商商城模板', t2Desc: '潮流设计，商品展示与购物体验并重',
    t3Title: '个人博客模板', t3Desc: '极简美学，专注内容呈现与阅读体验',
    t4Title: 'Landing Page 模板', t4Desc: '转化导向设计，适合产品发布与活动推广',
    priceFrom: '起',
    secProcess: '合作流程',
    processDesc: '透明高效，每一步都清晰可见',
    p1Title: '需求沟通', p1Desc: '了解你的业务目标、功能需求、设计偏好',
    p2Title: '方案 & 报价', p2Desc: '输出项目方案、时间规划与透明报价',
    p3Title: '设计定稿', p3Desc: 'UI 视觉设计，修改至满意后确认定稿',
    p4Title: '开发上线', p4Desc: '前端开发、测试、部署上线与交付',
    secPricing: '价格方案',
    pricingDesc: '透明定价，无隐藏费用',
    planPopular: '最受欢迎', planStarter: '基础版', planPro: '专业版', planEnterprise: '旗舰版',
    starter1: '5 个页面以内', starter2: '响应式设计', starter3: '基础 SEO 优化', starter4: '1 年免费维护', starter5: '标准交付 7 天',
    pro1: '10 个页面以内', pro2: '响应式设计', pro3: '深度 SEO 优化', pro4: '1 年免费维护', pro5: '后台管理系统', pro6: '标准交付 15 天',
    ent1: '不限页面数量', ent2: '定制 UI 设计', ent3: '全栈开发方案', ent4: '2 年免费维护', ent5: '数据库 + API 集成', ent6: '标准交付 30 天',
    choosePlan: '选择方案',
    secContact: '联系我们',
    contactDesc: '选择您偏好的联系方式，我们随时为您服务',
    contactGroup: 'Discord: 星域集团 AI帝国',
    ctaModalTitle: '立即咨询',
    ctaModalSub: '选择以下方式联系我们',
    ctaModalEmail: '发送邮件',
    ctaModalWA: 'WhatsApp 咨询',
    ctaModalClose: '关闭',
    footer1: '© 2026 WebHub · 星域集团。保留所有权利。',
    footer2: 'Powered by StellarElite Group',
  },
  en: {
    navServices: 'Services',
    navTemplates: 'Templates',
    navProcess: 'Process',
    navPricing: 'Pricing',
    navCTA: 'Get Started',
    heroTitle: 'Custom Your',
    heroHighlight: 'Own Website',
    heroSub: 'Professional custom development · Premium templates · Fully responsive design',
    heroBtn1: 'Explore Services',
    heroBtn2: 'Free Consultation',
    secServices: 'Our Services',
    servicesDesc: 'From personal brands to enterprise sites, we cover every need',
    sv1Title: 'Corporate Website', sv1Desc: 'Tailor-made enterprise brand websites with company profiles, product showcases, news, and contact modules.',
    sv2Title: 'E-Commerce Store', sv2Desc: 'Product display, shopping cart, online payments, order management — complete e-commerce solution.',
    sv3Title: 'Responsive Landing Pages', sv3Desc: 'Campaign promotions, product launches, brand stories — perfect on mobile, tablet, and desktop.',
    sv4Title: 'UI Design + Frontend Dev', sv4Desc: 'Professional UI design paired with high-quality frontend code, pixel-perfect implementation.',
    sv5Title: 'Maintenance & Optimization', sv5Desc: 'Content updates, performance tuning, security hardening, and SEO optimization.',
    sv6Title: 'Mini Program Development', sv6Desc: 'WeChat and Alipay mini programs, seamlessly integrated with your website data.',
    tagPopular: 'Popular', tagRecommended: 'Recommended', tagNew: 'New',
    secTemplates: 'Featured Templates',
    templatesDesc: 'Ready to use, fast to launch, professional design quality',
    t1Title: 'Corporate Template', t1Desc: 'Elegant and professional style, ideal for manufacturing, tech, and service industries',
    t2Title: 'E-Commerce Template', t2Desc: 'Trendy design balancing product showcase with shopping experience',
    t3Title: 'Blog Template', t3Desc: 'Minimalist aesthetics focused on content presentation and reading experience',
    t4Title: 'Landing Page Template', t4Desc: 'Conversion-oriented design, perfect for product launches and campaigns',
    priceFrom: 'From ',
    secProcess: 'Our Process',
    processDesc: 'Transparent and efficient — every step clearly visible',
    p1Title: 'Discovery', p1Desc: 'Understand your business goals, functional needs, and design preferences',
    p2Title: 'Proposal & Quote', p2Desc: 'Project plan, timeline, and transparent pricing',
    p3Title: 'Design Approval', p3Desc: 'UI visual design with revisions until you\'re satisfied',
    p4Title: 'Development & Launch', p4Desc: 'Frontend development, testing, deployment, and handover',
    secPricing: 'Pricing Plans',
    pricingDesc: 'Transparent pricing with no hidden fees',
    planPopular: 'Most Popular', planStarter: 'Starter', planPro: 'Professional', planEnterprise: 'Enterprise',
    starter1: 'Up to 5 pages', starter2: 'Responsive design', starter3: 'Basic SEO', starter4: '1 year maintenance', starter5: '7-day delivery',
    pro1: 'Up to 10 pages', pro2: 'Responsive design', pro3: 'Advanced SEO', pro4: '1 year maintenance', pro5: 'Admin dashboard', pro6: '15-day delivery',
    ent1: 'Unlimited pages', ent2: 'Custom UI design', ent3: 'Full-stack development', ent4: '2 years maintenance', ent5: 'Database + API', ent6: '30-day delivery',
    choosePlan: 'Choose Plan',
    secContact: 'Contact Us',
    contactDesc: 'Choose your preferred way to reach us — we\'re here to help',
    contactGroup: 'Discord: StellarElite Group',
    ctaModalTitle: 'Get in Touch',
    ctaModalSub: 'Choose a channel to reach us',
    ctaModalEmail: 'Send Email',
    ctaModalWA: 'WhatsApp Chat',
    ctaModalClose: 'Close',
    footer1: '© 2026 WebHub · StellarElite Group. All rights reserved.',
    footer2: 'Powered by StellarElite Group',
  }
};
